### ISSUE TITLE
TypeError: jwt_decode__WEBPACK_IMPORTED_MODULE_5__ is not a function

### ISSUE THREAD

**Issue by grizzlysol** [auth0/jwt-decode#97] opened 2020-09-29 15:58 UTC
When using jwt-decode I receive this error: "TypeError: jwt_decode__WEBPACK_IMPORTED_MODULE_5__ is not a function"
I have been using jwt-decode for many years and am currently using jwt-decode version **3.0.0-beta.2** and recently upgraded to Angular 10 (v10.1.3) using the angular update tool in Angular CLI

```
import * as jwt_decode from 'jwt-decode';

export class AuthService {
...
  decode(token: string): any {
    return jwt_decode(token);
  }
...
}
```

Not sure if this actually has anything to do with webpack as the error suggests, but I am on versions
"webpack": "^4.44.2",
"webpack-cli": "^3.3.12"

I also tryed installing the type defs for jwt-decode, but they haven't fixed anything
"@types/jwt-decode": "^2.2.1",

**Comment by Sambego** [comment] 2020-09-29 16:46
This might be a duplicate of #96 

Try importing the library as `import jwt_decode from 'jwt-decode';`

**Comment by grizzlysol** [comment] 2020-09-29 17:18
That seems to fix the issue. Is this issue understood? 
As, I said I've been using jwt-decode for many years and never had any issues with this. Maybe something in another dependency?

**Comment by Sambego** [comment] 2020-09-29 17:34
`jwt_decode` has always been a CommonJS module which generally are imported as `const jwt_decode = require('jwt-decode');`, it's what Node.js uses. 

The way to import CommonJS libraries with a JS `import` statement is `import * as library-name from 'library-name;`.

Modern frameworks like Angular 10 throw a warning when using packages with the CommonJS format, because they generally speaking can't be tree-shaked.

Version 3 (now in beta) of this library includes a more modern ESM build, which is what JS import statements are meant for, so importing the modern ESM package can be done the regular way using `import jwt_decode from 'jwt-decode';`. This is a breaking change, that's why I've created a new major version `3`.

We still have a CommonJS build, but by default most modern build systems for the web (not node) will use the ESM build. 

if you checkout the `package.json` file when installing the lib, you'll notice both builds in there.

```
{
    ...
    "main": "build/jwt-decode.cjs.js",
    "module": "build/jwt-decode.esm.js",
    ...
}
```

I hope this helps :)

**Comment by Sambego** [comment] 2020-09-29 17:35
I'm updating the docs soon, to indicate this change when importing.

**Closed by Sambego** 2020-09-29 17:34 UTC

**Comment by grizzlysol** [comment] 2020-09-29 17:45
Thank you for the explanation. I see now that I updated to the most recent version of jwt-decode without realizing. 
Thanks for keeping the project maintained! :)

**Comment by EdinsonUwU** [comment] 2024-07-30 18:08
If you are in react, you can import it like this:

```typescript
import { jwtDecode } from 'jwt-decode';
``` `

instead of: 
```typescript
import jwtDecode from 'jwt-decode';
``` `
