### ISSUE TITLE
jwt decode is not working in react native

### ISSUE THREAD

**Issue by vish3232** [auth0/jwt-decode#291] opened 2023-12-24 07:01 UTC
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/jwt-decode#readme) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/jwt-decode/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

if i install jwt decode npm library in react native then it not working they are giving error of atob does not exits if o import that then they cause another problem for navigation

### Reproduction

npm install jwt-decode
import {jwtDecode} from 'wt-decode'
const decode = jwtDecode('token')

### Additional context

ljkbl

### jwt-decode version

4.0.0

### Which browsers have you tested in?

Chrome, Other

**Comment by jonkoops** [comment] 2023-12-24 13:11
Duplicate of #241, see also the [polyfilling section](https://github.com/auth0/jwt-decode#polyfilling-atob) of the README.

**Comment by frederikprijck** [comment] 2023-12-24 15:50
Closing because duplicate.

**Closed** 2023-12-24 15:50 UTC
Labels: bug
